# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdad8bc138e7d822fd4b92134fbaa90ae8ff98fb0fb44607d3f73ba0ce0cbeb6eb0fec55d0df7a61bbf7df0dd5fdaef3a1d74f345b346929559eeb9240bea753

test:
  secret_key_base: e6e9a28a7f0eddf690d92db939c38e21fd7adf117a3937e5cdcce45451150a4348a3fcddc0e73eaae23107dbe3aab8ac353e479fbc8a481df12d62a4ec285a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
